name: release-tag-installer-pre-upgrade-2-6-0

on:
  push:
    tags: 
    - 'pre-upgrade-2-6-0/[0-9]+.[0-9]+.[0-9]+'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GitHub App
        id: authenticate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract version
        run: |
          CHART_VERSION=${GITHUB_REF#refs/tags/pre-upgrade-2-6-0/}
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Print Version
        run: |
          echo CHART_VERSION:${{ env.CHART_VERSION }}

      - name: Replace CHART_VERSION in pre-upgrade-2-6-0-chart/Chart.yaml
        run: sed -i 's/CHART_VERSION/${{ env.CHART_VERSION }}/g' ./pre-upgrade-2-6-0-chart/Chart.yaml

      # Stage only the chart you want to publish
      - name: Prepare charts_dir
        run: |
          mkdir -p _pre-upgrade-2-6-0-chart
          cp -R pre-upgrade-2-6-0-chart _pre-upgrade-2-6-0-chart/

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ steps.authenticate.outputs.token }}
          charts_dir: _pre-upgrade-2-6-0-chart
          charts_url: https://charts.krateo.io
          owner: krateoplatformops
          repository: helm-charts
          branch: gh-pages